# Generated by Django 3.2 on 2022-08-29 12:11

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('state', django_fsm.FSMField(default='receive', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiamondWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diamond')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='diamond',
            name='workflows',
            field=models.ManyToManyField(through='app.DiamondWorkflow', to='workflow.Workflow'),
        ),
    ]
